### ISSUE TITLE
Strange failure

### ISSUE THREAD

**Issue by MBkkt** [jidicula/clang-format-action#101]
https://github.com/YACLib/YACLib/runs/7003917329?check_suite_focus=true
https://github.com/YACLib/YACLib/blob/main/.github/workflows/format.yml
Can you help?

**Comment by MBkkt** [comment]
https://github.com/jidicula/clang-format-action/pkgs/container/clang-format

**Comment by MBkkt** [comment]
Sorry, it was failure on GitHub side

**Comment by jidicula** [comment]
> ![image](https://user-images.githubusercontent.com/32071355/175030344-facd6f25-6dc5-4f8c-b56c-7eb65b5578e4.png)
> What did change 8 hours ago?

I rebuild the containers with the same `clang-format` major version tag daily and delete the dangling containers, which pulls in any non-breaking releases for `clang-format`.
