### ISSUE TITLE
clang-format-version does not accept 6.0 or 5.0 or 4.0 or 3.9

### ISSUE THREAD

**Issue by mloskot** [jidicula/clang-format-action#134]
The README lists these versions as supported, but it looks like the `clang-format-version` expects the MAJOR part only, e.g. because of this test
https://github.com/jidicula/clang-format-action/blob/134f65822ca35d45f96eed815d275534ab504f20/check.sh#L23

![image](https://user-images.githubusercontent.com/80741/216769842-801432a2-4db1-4f3a-b4fe-bd4f14f405c5.png)

**Comment by jidicula** [comment]
Woops, yeah - I'll update the README.
