### ISSUE TITLE
GH container registry 503 error

### ISSUE THREAD

**Issue by aea7** [jidicula/clang-format-action#140]
Hey, I get a 503 error trying to fetch https://ghcr.io/v2/jidicula/clang-format/manifests/15 wanted to bring it to your attention 👍🏼

**Comment by Myoldmopar** [comment]
Our builds just started failing this morning as well with the following...I don't see 503 explicitly, but I assume it's the same issue:

```
Run jidicula/clang-format-action@v4.10.1
  with:
    clang-format-version: 10
    check-path: src/EnergyPlus
    fallback-style: llvm
Run "/home/runner/work/_actions/jidicula/clang-format-action/v4.10.1/check.sh" "10" "src/EnergyPlus" "llvm" "" ""
  "/home/runner/work/_actions/jidicula/clang-format-action/v4.10.1/check.sh" "10" "src/EnergyPlus" "llvm" "" ""
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Unable to find image 'ghcr.io/jidicula/clang-format:10' locally
docker: Error response from daemon: Head "https://ghcr.io/v[2](https://github.com/NREL/EnergyPlus/actions/runs/4427506300/jobs/7765193171#step:3:2)/jidicula/clang-format/manifests/10": Get "https://ghcr.io/token?scope=repository%[3](https://github.com/NREL/EnergyPlus/actions/runs/4427506300/jobs/7765193171#step:3:3)Ajidicula%2Fclang-format%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

If it's not the same then I can open a separate issue.

**Comment by jidicula** [comment]
@Myoldmopar I'm not able to reproduce this in https://github.com/jidicula/test-clang-format-action/actions/runs/4428271920/jobs/7767104502 . Can you try triggering a re-run on the [failed run](https://github.com/NREL/EnergyPlus/actions/runs/4427506300/jobs/7765193171) and see if it happens again?

The 503 issue could be an intermittent issue with GHCR.

**Comment by Myoldmopar** [comment]
Looks like it is working again, just a fluke!  Thanks for the reply, and for this GH action, we really appreciate it!

**Comment by jidicula** [comment]
@aea7 could you retry your workflow run as well to see if it was just an intermittent 503 being returned by GHCR?

**Comment by jidicula** [comment]
I suspect this failure was related to [this incident with Packages](https://www.githubstatus.com/incidents/ybnn77s3lyf8?utm_ts=1678894046) a few hours ago.

**Comment by Myoldmopar** [comment]
I'm sure you are right, and I'm also sure you weren't the only random repo owner getting harassed by users! :D  

Thanks again

**Comment by Myoldmopar** [comment]
I'm sure you are right, and I'm also sure you weren't the only random repo owner getting harassed by users! :D  

Thanks again

**Comment by aea7** [comment]
> @aea7 could you retry your workflow run as well to see if it was just an intermittent 503 being returned by GHCR?

yep, it's working now, apparently ghrc was down looking at the incident that you mentioned. @jidicula
