### ISSUE TITLE
feat: allow the workflow to specify the minor & patch version

### ISSUE THREAD

**Issue by Disservin** [jidicula/clang-format-action#168]
Hi,

I think it would be great if the action also exposes a way to define the minor and patch version,  
so that the version of clang-format is fixed.  
Currently the version may change depending on what ubuntu currently distributes. 
clang-format 17 uses this version right now https://packages.ubuntu.com/mantic/clang-format-17. 

Edit: The action is also a bit of a blackbox, when you specify it's not clear directly which exact version was used for the format check. One needs to check the current distributed version from the link above which is a might annoying, can the workflow maybe expose the current version which is printed by `clang-format --version` ?

**Comment by jidicula** [comment]
Thanks for this feedback and for using my action! I want to gather some more data about this in https://github.com/jidicula/clang-format-action/discussions/192, so I'd love to get your vote and an optional comment sharing more details so I can understand this problem better.

**Comment by jidicula** [comment]
I'm going to close this as completed with https://github.com/jidicula/clang-format-action/pull/195 and in the meantime I'll gather more data about minor+patch version specification needs in https://github.com/jidicula/clang-format-action/discussions/192
