### ISSUE TITLE
Support C++ files

### ISSUE THREAD

**Issue by jidicula** [jidicula/clang-format-action#18]
> What do you think of supporting C++ as well?

That would be cool! I'm not well-versed with C++ - would that just involve adding `.cpp` [here](https://github.com/jidicula/clang-format-action/blob/e990d5b7c2205aacdd3a49d4b632843769c8f3e7/entrypoint.sh#L37)?

__Originally posted by @jidicula in https://github.com/jidicula/clang-format-action/issues/9#issuecomment-751125028__

Todo for @jidicula: create a new release once this has been closed

**Comment by jidicula** [comment]
@Bartekpacia are you up for tackling this ticket?

**Comment by bartekpacia** [comment]
Currently, I don't have enough time, sorry and merry Christmas ;)

**Comment by jidicula** [comment]
> Currently, I don't have enough time, sorry and merry Christmas ;)

No worries, Merry Christmas to you too!
