### ISSUE TITLE
Add support for clang-format-18

### ISSUE THREAD

**Issue by DeveloperPaul123** [jidicula/clang-format-action#188]
LLVM 18 is released now and it would be nice to have support for `clang-format-18`. It's currently available on [Ubuntu noble](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=clang-format-18&searchon=names).

**Comment by jidicula** [comment]
I actually added this a while back in https://github.com/jidicula/clang-format-action/pull/183. I've just cut a new release for this - thanks for the nudge 😁: https://github.com/jidicula/clang-format-action/releases/tag/v4.12.0
