### ISSUE TITLE
Search Directory Prefix

### ISSUE THREAD

**Issue by philberty** [jidicula/clang-format-action#27]
I would like to use this plugin on gccrs but not all of gcc is fully compliant to the clang format config there. So it would be nice to point the checker to a single directory to recursively check each source file there.

**Comment by jidicula** [comment]
Sure, I can absolutely add that functionality. I expect that I'll only get around to it by this weekend - if that's too long, there's [another action](https://github.com/DoozyX/clang-format-lint-action) that can already do what you want.

**Comment by jidicula** [comment]
@philberty please see the changes in the example workflow in the README [here](https://github.com/jidicula/clang-format-action/blob/dev/README.md). I've also just published a new release for this, so you should have access to this feature if you use the `v3.0.0` tag.

**Comment by philberty** [comment]
Thanks for this i will give it a whirl :+1:
