### ISSUE TITLE
check additional file types

### ISSUE THREAD

**Issue by nealtanner** [jidicula/clang-format-action#57]
I am using this action on a project that includes arduino source code, which follows C++ syntax but likes to have an `.ino` extension.  Is this a common enough use case to include `.ino` in the default list of file types checked or would it make more sense to pass in another argument to override the default include regex?

I'm happy to implement something and put a PR, but wanted to check on your preferred approach first.

**Comment by nealtanner** [comment]
@jidicula, sorry I hadn't gotten to this yet.  Thanks for adding it.

**Comment by jidicula** [comment]
No problem, let me know if you run into any issues with it 🙂
