### ISSUE TITLE
Trouble with branchnames that end in .cpp

### ISSUE THREAD

**Issue by jotoho** [jidicula/clang-format-action#66]
Working on a branch whose name ends in .cpp causes this action to misbehave. I suspect that it is picking up on some git-internal file(s) in the .git directory and incorrectly believes them to be C++ source files. This may also happen with similar extensions like .h, .hpp and .c files though I have not tested that.

**Comment by jidicula** [comment]
For now, can you try adding the `.git` directory as an arg to the `exclude-regex` input and see if that solves the issue?

I'll add it to the main regex in the bugfix for this.

**Comment by jotoho** [comment]
@jidicula I began looking for a patch for this small bug directly after creating the issue here. I think that I've got a solution and submitted it in #67. Feel free to close it if you've got a better idea on how to handle this.
