### ISSUE TITLE
Add option for customizing file extensions

### ISSUE THREAD

**Issue by Krzmbrzl** [jidicula/clang-format-action#79]
Now that the last issue is resolved, let me continue complaining :D 

It would be nice if there was an additional option to this action that would allow to specify a set of file extensions for files to check. This could default to the current list of files, but gives the user more flexibility in terms of which files are to be checked by this action.
In that step it would probably also be nice to make the regex parsing used for finding the files with given extension case-insensitive, such that one does not have to worry about casing when specifying file extensions.

**Comment by nmoinvaz** [comment]
This would be good for Objective-C which uses `*.m` file extension for implementation files.

**Comment by bcaddy** [comment]
I would also like this. Our codebase uses a lot of CUDA and so we need to be able to format `.cu` and `.hu` files.

**Comment by scosman** [comment]
If anyone needs a fork adding `.m files` (this just statically adds `.m`, not option to customize as issue requests): https://github.com/scosman/clang-format-action 

Use this line in your yml: `uses: scosman/clang-format-action@v0.1`

But agree, official support for a custom extension list would be ideal!

**Comment by jidicula** [comment]
Addressed in #125 🙂. Sorry that it took so long for me to get around to this! 4.10.0 release contains this feature.
