### ISSUE TITLE
Clang-format 11

### ISSUE THREAD

**Issue by bartekpacia** [jidicula/clang-format-action#9]
as the title says.

I'm using another GH Action because this one doesn't support v11.

**Comment by jidicula** [comment]
Hey, thanks for submitting an issue! It's been a while since I've worked on this but I'll try to add support for this (or even version choice) in the coming days. Of course, you're always free to submit a PR 😁 .

**Comment by bartekpacia** [comment]
okay, I'll create a PR :)

**Comment by jidicula** [comment]
> okay, I'll create a PR :)

Sure, take a crack at it, I've updated my comment with some subtasks that will be needed 😄. Let me know if you get stuck and I can try to help you as well.

**Comment by bartekpacia** [comment]
What do you think of supporting C++ as well?

**Comment by jidicula** [comment]
> What do you think of supporting C++ as well?

That would be cool! I'm not well-versed with C++ - would that just involve adding `.cpp` [here](https://github.com/jidicula/clang-format-action/blob/e990d5b7c2205aacdd3a49d4b632843769c8f3e7/entrypoint.sh#L37)?

**Comment by bartekpacia** [comment]
well, I'm a C++ n00b, but I'm pretty sure that it would work just fine:)

**Comment by jidicula** [comment]
> well, I'm a C++ n00b, but I'm pretty sure that it would work just fine:)

Awesome, I'll cut a new ticket for it.

**Comment by jidicula** [comment]
@bartekpacia this feature is added in v3.1.0 if you'd like to give it a try 😄
